### ISSUE TITLE
Tabs keep reloading on revisit even though Auto-discardable is disabled/crossed

### ISSUE THREAD

**Issue by Neurovert** [WorldLanguages/DoNotDiscard#1]
Like the topic says :( 

@WorldLanguages can you please verify this yourself? 
My Chrome details:

> Google Chrome | 77.0.3865.75 (Official Build) (64-bit)
> -- | --
> Revision | 201e747d032611c5f2785cae06e894cf85be7f8a-refs/branch-heads/3865@{#776}
> OS | Linux

I also have Proactive Tab Freeze and Discard disabled

> Proactive Tab Freeze and Discard
> Enables proactive tab freezing and discarding. This requires #enable-page-almost-idle. – Mac, Windows, Linux, Chrome OS
> 
> #proactive-tab-freeze-and-discard

**Comment by WorldLanguages** [comment]
I think Chrome will still discard tabs via "urgent discarding" if it needs to.
You can check if the extension is working by going to chrome://discards and checking there's a cross in the "auto discardable" column, for every tab. If that's the case, the extension is doing all it can to avoid discarding. It really can't do more.
